export const products = [
  {
    id: '1',
    title: 'Background fabric Falcon Black 2.7x5 m',
    type: 'Background',
    material: 'Fabric',
    dimension: '2.7 x 5 m',
    color: 'Black',
    warranty: '14 days',
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 42,
    price: '300',
  }, {
    id: '2',
    title: 'Background fabric Falcon White 2.4х2.7 m',
    type: 'Background',
    material: 'Fabric',
    dimension: '2.4 x 2.7 m',
    color: 'White',
    warranty: '12 months',
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 11,
    price: '5345'
  }, {
    id: '3',
    title: 'Background fabric Falcon green 2.7x5.0 m (Chromakey)',
    type: 'Background',
    material: 'Fabric',
    dimension: '2.7 x 5 m',
    color: 'Green',
    warranty: '14 days',
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 31,
    price: '2324'
  }, {
    id: '4',
    title: 'Background fabric Falcon on a spring of 158х193 cm (Chromakey Green-Gray)',
    type: 'Background',
    material: 'Fabric',
    dimension: '1.58 x 1.93 m',
    color: 'Green',
    warranty: '12 months',
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 2,
    price: '1214'
  }, {
    id: '5',
    title: 'Background fabric green for Chromakey photo studio 1.5x2.2 m',
    type: 'Background',
    material: 'Fabric',
    dimension: '1.5x2.2 m',
    color: 'Green',
    warranty: null,
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 0,
    price: '5764'
  }, {
    id: '6',
    title: 'Background for subject shooting Puluz PKT5200 120x60cm black',
    type: 'Background',
    material: 'Vinyl',
    dimension: '120 x 60 cm',
    color: 'Black',
    warranty: null,
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 66,
    price: '9923'
  }, {
    id: '7',
    title: 'Background fabric MyGear green chromakey WOB-2002 - 3x3 m',
    type: 'Background',
    material: 'Fabric',
    dimension: '3x3 m',
    color: 'Green',
    warranty: null,
    countryOfOrigin: 'China',
    brandCountry: 'China',
    maxQuantity: 66,
    price: '3535'
  }
]